### ISSUE TITLE
background scanning on iOS9

### ISSUE THREAD

**Issue by mbillau** [presence-insights/pi-clientsdk-ios#30]
See this thread about issues with background scanning for BLE devices on iOS 9

https://forums.developer.apple.com/thread/19746

**Comment by lizeray** [comment]
The IBMPIBeaconSDK must work without any background mode. This is a very strong requirement. No need to have Location Update and BLE Central background modes for beacons.

**Comment by mbillau** [comment]
@lizeray I have seen it work in the background on iOS 9, can you confirm?

**Comment by lizeray** [comment]
@mbillau I am not sure to understand the question?

**Comment by mbillau** [comment]
@lizeray hi, you say: "IBMPIBeaconSDK must work without any background mode. This is a very strong requirement."

I have seen things work in the background with the current version of the SDK - have you? If so, can we close this issue?

**Comment by lizeray** [comment]
I have created the issue because the pizzeria demo has the GPS and BLE accessories background modes enabled.
Once this demo is running without any background mode, we can close this issue, not before.
Thanks

**Comment by CiaranHannigan** [comment]
@mbillau this issue is in regards to [Background Modes](https://developer.apple.com/library/ios/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html). In our case, in iOS 9 we have a [condition](https://github.com/presence-insights/pi-clientsdk-ios/blob/master/PresenceInsightsSDK/RegionManager.swift#L50) that sets allowsBackgroundLocationUpdates to true. This gives us the ability to continually range in the background, as if our app was still in the foreground. This is functionality that a GPS app would require, or a fitness app tracking your distance and route.

The major issue with this is that Apple will more than likely reject an app using our SDK. My guess is that they would cite that it does not provide sufficient benefit to the app user.

**Comment by lizeray** [comment]
@CiaranHannigan We don't need to use this property for doing background ranging for 10 seconds....

**Comment by CiaranHannigan** [comment]
Correct, I am stating that we need to stay with our solution of relying on callbacks to get some time to range in the background, and not use Background Modes.

**Comment by CiaranHannigan** [comment]
https://github.com/presence-insights/pi-clientsdk-ios/pull/41
